#!/usr/bin/env python3
"""
Auto Spine Survey v2.1 - Build Script
Builds GUI executable using PyInstaller.

Usage:
    python scripts/build_executable.py
"""

import json
import shutil
import subprocess
import sys
from pathlib import Path

VERSION = "2.1"
APP_NAME = "AutoSpineSurvey"

# Data files to bundle (paths relative to project root)
DATA_FILES = [
    ("data/page_instruction.json", "data"),
    ("data/eq5d_value_k.csv", "data"),
    ("config.json", "."),
    (".env.example", "."),
]

# Files that must NEVER be included in builds (contain user data)
EXCLUDED_FILES = [".env"]

HIDDEN_IMPORTS = [
    "cv2",
    "numpy",
    "pandas",
    "openai",
    "anthropic",
    "PIL",
    "fitz",
    "dotenv",
    "json",
    "logging",
    "base64",
    "typing",
    "core",
    "core.config",
    "core.base_processor",
    "core.claude_processor",
    "core.openai_processor",
    "core.pdf_processor",
    "core.csv_generator",
    "core.validators",
    # NiceGUI / web stack
    "nicegui",
    "nicegui.elements",
    "nicegui.events",
    "webview",
    "fastapi",
    "uvicorn",
    "uvicorn.logging",
    "uvicorn.loops",
    "uvicorn.loops.auto",
    "uvicorn.protocols",
    "uvicorn.protocols.http",
    "uvicorn.protocols.http.auto",
    "uvicorn.protocols.websockets",
    "uvicorn.protocols.websockets.auto",
    "uvicorn.lifespan",
    "uvicorn.lifespan.on",
    "socketio",
    "engineio",
    "aiofiles",
    "httpx",
    "threading",
    "asyncio",
    "webbrowser",
]


def get_project_root() -> Path:
    """Return the project root directory (parent of scripts/)."""
    return Path(__file__).resolve().parent.parent


def check_prerequisites():
    """Verify PyInstaller is installed and project files exist."""
    try:
        import PyInstaller  # noqa: F401
        print(f"[OK] PyInstaller {PyInstaller.__version__}")
    except ImportError:
        print("[FAIL] PyInstaller not installed. Run: pip install pyinstaller")
        sys.exit(1)

    root = get_project_root()
    if not (root / "app.py").exists():
        print(f"[FAIL] app.py not found in {root}")
        sys.exit(1)

    for data_file, _ in DATA_FILES:
        if not (root / data_file).exists():
            print(f"[WARN] Data file missing: {data_file}")

    print(f"[OK] Project root: {root}")


def get_nicegui_data_path() -> list:
    """Locate NiceGUI package data for bundling."""
    try:
        import nicegui
        ng_path = Path(nicegui.__file__).parent
        return [(str(ng_path), "nicegui")]
    except ImportError:
        print("[WARN] nicegui not found; build may fail")
        return []


def create_spec_content() -> str:
    """Generate PyInstaller .spec file content."""
    root = get_project_root()

    # Build datas list
    datas_lines = []
    for data_file, dest in DATA_FILES:
        if (root / data_file).exists():
            datas_lines.append(f"    ('{data_file}', '{dest}'),")

    # Bundle core/ and gui_ng/ packages
    datas_lines.append("    ('core/', 'core/'),")
    datas_lines.append("    ('gui_ng/', 'gui_ng/'),")

    # Add NiceGUI resources (static assets, templates)
    ng_data = get_nicegui_data_path()
    for src, dst in ng_data:
        datas_lines.append(f"    (r'{src}', '{dst}'),")

    datas_str = "\n".join(datas_lines)

    # Build hidden imports
    imports = list(HIDDEN_IMPORTS)
    if sys.platform == "win32":
        imports.append("tkinterdnd2")

    imports_str = ",\n".join(f"    '{imp}'" for imp in imports)

    spec = f"""# -*- mode: python ; coding: utf-8 -*-
# Auto-generated by build_executable.py v{VERSION}

block_cipher = None

datas = [
{datas_str}
]

hiddenimports = [
{imports_str},
]

a = Analysis(
    ['app.py'],
    pathex=[],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='{APP_NAME}',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
    windowed=True,
)
"""
    return spec


def build() -> bool:
    """Build GUI executable."""
    root = get_project_root()
    spec_filename = f"{APP_NAME}.spec"
    spec_path = root / spec_filename

    print(f"\n{'=' * 50}")
    print(f"Building {APP_NAME}")
    print(f"{'=' * 50}")

    # Write spec file
    spec_content = create_spec_content()
    spec_path.write_text(spec_content, encoding="utf-8")
    print(f"[OK] Spec file: {spec_filename}")

    # Run PyInstaller from project root
    cmd = [
        sys.executable, "-m", "PyInstaller",
        "--clean",
        str(spec_path),
    ]

    print("[..] Running PyInstaller...")
    result = subprocess.run(cmd, capture_output=True, text=True, cwd=str(root))

    if result.returncode != 0:
        print(f"[FAIL] Build failed for {APP_NAME}")
        print("STDOUT:", result.stdout[-2000:] if len(result.stdout) > 2000 else result.stdout)
        print("STDERR:", result.stderr[-2000:] if len(result.stderr) > 2000 else result.stderr)
        return False

    print(f"[OK] Build succeeded: dist/{APP_NAME}")

    # Clean up spec file
    spec_path.unlink(missing_ok=True)

    return True


def create_portable_package() -> bool:
    """Create a portable distribution package."""
    root = get_project_root()
    package_dir = root / f"{APP_NAME}_Portable"

    print(f"\n[..] Creating portable package: {package_dir.name}")

    # Clean previous package
    if package_dir.exists():
        shutil.rmtree(package_dir)
    package_dir.mkdir()

    # Copy executable
    exe_name = f"{APP_NAME}.exe" if sys.platform == "win32" else APP_NAME
    exe_source = root / "dist" / exe_name
    if not exe_source.exists():
        print(f"[FAIL] Executable not found: {exe_source}")
        return False
    shutil.copy2(exe_source, package_dir)

    # Copy config.json (no API keys — keys are in .env only)
    config_path = root / "config.json"
    if config_path.exists():
        shutil.copy2(config_path, package_dir / "config.json")

    # Copy .env.example
    env_example = root / ".env.example"
    if env_example.exists():
        shutil.copy2(env_example, package_dir / ".env.example")

    # Copy data files (excluding secrets)
    (package_dir / "data").mkdir(exist_ok=True)
    for data_file in ["data/page_instruction.json", "data/eq5d_value_k.csv"]:
        src = root / data_file
        if src.exists():
            shutil.copy2(src, package_dir / data_file)

    # Create working directories
    for folder in ["input_pdfs", "output_csv", "temp_images", "logs"]:
        (package_dir / folder).mkdir(exist_ok=True)

    # Write portable README
    readme = f"""Auto Spine Survey v{VERSION} - Portable Package

Setup
-----
1. Copy .env.example to .env and fill in your API keys:
   - CLAUDE_API_KEY for Claude (Anthropic)
   - OPENAI_API_KEY for OpenAI

2. Edit config.json to select your provider ("claude" or "openai").

3. Place PDF survey files in the input_pdfs/ folder.

Usage
-----
- Windows: Double-click {exe_name}
- macOS/Linux: ./{APP_NAME}

Results are saved to output_csv/. Logs are in logs/.

Supported Surveys: VAS, ODI, EQ-5D-5L, painDETECT
Supported Models: Claude Haiku 4.5, GPT-5 mini
"""
    (package_dir / "README.txt").write_text(readme, encoding="utf-8")

    print(f"[OK] Portable package: {package_dir.name}/")
    for item in sorted(package_dir.rglob("*")):
        rel = item.relative_to(package_dir)
        prefix = "  dir " if item.is_dir() else "  file"
        print(f"  {prefix} {rel}")

    return True


def main():
    print(f"Auto Spine Survey v{VERSION} - Build Script")
    print("=" * 50)

    check_prerequisites()

    if not build():
        sys.exit(1)
    if not create_portable_package():
        sys.exit(1)

    # Clean up build artifacts
    root = get_project_root()
    for cleanup_dir in ["build"]:
        d = root / cleanup_dir
        if d.exists():
            shutil.rmtree(d)

    print(f"\n{'=' * 50}")
    print("Build completed successfully!")
    print(f"  Portable package: {APP_NAME}_Portable/")
    print("=" * 50)


if __name__ == "__main__":
    main()
